<script type="text/javascript" src="//yandex.st/share/share.js" charset="utf-8"></script>

<div class="social-buttons">
    <div class="google-plusone"><div class="g-plusone" data-size="standard" data-count="true"></div></div>
    <div class="yashare-auto-init" data-yashareL10n="ru" data-yashareType="icon" data-yashareQuickServices="yaru,vkontakte,facebook,twitter,odnoklassniki,moimir,lj"></div>
</div>