<!doctype html>
<html>
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
    <title><?php echo $title; ?></title>
    <link href="/css/main.css" rel="stylesheet" />
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <script type="text/javascript" src="https://apis.google.com/js/plusone.js"></script>
<script type="text/javascript">/*<![CDATA[*/

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-6037428-13']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

/*]]>*/</script>
<script type="text/javascript" src="http://userapi.com/js/api/openapi.js?41"></script>
<script type="text/javascript">
  VK.init({apiId: 2669474, onlyWidgets: true});
</script>
</head>
<body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) {return;}
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/ru_RU/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div id="wrapper">

<?php echo $body; ?>

    <div id="footer">
        <p class="copyright">&copy; 2011 <a href="/" title="На главную страницу">Anal Entry</a> / Вход в жопу</p>
        <p class="version">ver. 0.4 beta</p>
    </div>
</div>
</body>
</html>